### ISSUE TITLE
Installation on Test Server

### ISSUE THREAD

**Issue by MarcusCaeruleus** [froger-me/wp-weixin-pay#1]
Alexandre,

I am having trouble getting this plugin to work on my test server which only has an IP address and no domain name. Is this an expected issue or have I set something up incorrectly?

Best regards,

Mark

**Comment by froger-me** [comment]
Hello @MarcusCaeruleus and thank you for your message!

I am not extensively familiar with sandboxing when developing with WeChat - I do know they provide some tools for developers, but I have not used them, since the majority are in Chinese and difficult to translate.

In any case, all the sandbox tools I saw still require to interact with a server that has an ICP license, and with a domain name - the difference is that payments would not really happen.

If you want to test WP Weixin Pay, I recommend installing the plugin on a site under subdomain of your main domain, or in a subdirectory of your webroot, and if you're concerned with public access, you could put it behind a password protected area, frontend included. 
This way, you could register your URLs in the WeChat backends (mp.weixin.qq.com and pay.weixin.qq.com), and fill in all the appropriate settings for WP Weixin and WP Weixin Pay. Then it's just a matter of testing payments with the minimum amount (RMB 0.01).

**Comment by MarcusCaeruleus** [comment]
@froger-me Thanks for the advice. The test server doesn't have an ICP number, so that may be the issue. I'll have a think and plan how I can test it in the way you suggested. 

Very grateful that you have done the hard work in putting this plugin together!
